[package]
name = "attic-client"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "attic"
path = "src/main.rs"

[dependencies]
attic = { path = "../attic" }

anyhow = "1.0.69"
async-channel = "1.8.0"
bytes = "1.4.0"
clap = { version = "4.1", features = ["derive"] }
clap_complete = "4.1.4"
const_format = "0.2.30"
dialoguer = "0.10.3"
displaydoc = "0.2.3"
enum-as-inner = "0.5.1"
futures = "0.3.26"
humantime = "2.1.0"
indicatif = "0.17.3"
lazy_static = "1.4.0"
notify = { version = "5.1.0", default-features = false, features = ["macos_kqueue"] }
regex = "1.7.1"
reqwest = { version = "0.11.14", default-features = false, features = ["json", "rustls-tls", "rustls-tls-native-roots", "stream"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
toml = "0.7.2"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
xdg = "2.4.1"

[dependencies.tokio]
version = "1.26.0"
features = [
	"fs",
	"io-util",
	"macros",
	"process",
	"rt",
	"rt-multi-thread",
	"sync",
]
