[package]
name = "attic"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-stream = { version = "0.3.4", optional = true }
base64 = "0.21.0"
bytes = "1.4.0"
displaydoc = "0.2.3"
digest = "0.10.6"
ed25519-compact = "2.0.4"
futures = "0.3.26"
hex = "0.4.3"
lazy_static = "1.4.0"
log = "0.4.17"
nix-base32 = { git = "https://github.com/zhaofengli/nix-base32.git", rev = "b850c6e9273d1c39bd93abb704a53345f5be92eb" }
regex = "1.7.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9.18"
serde_with = "2.2.0"
sha2 = "0.10.6"
tempfile = "3"
wildmatch = "2.1.1"
xdg = "2.4.1"

# Native libnixstore bindings.
cxx = { version = "1.0", optional = true }

[dependencies.tokio]
version = "1.26.0"
optional = true
features = [
	"fs",
	"io-util",
	"process",
	"sync",
]

[dev-dependencies]
serde_json = "1.0.93"
tokio-test = "0.4.2"

[build-dependencies]
bindgen = { version = "0.64.0", optional = true }
cxx-build = { version = "1.0", optional = true }
pkg-config = "0.3.26"

[features]
default = [ "nix_store", "tokio" ]

# Native libnixstore bindings.
#
# When disabled, the native Rust portions of nix_store can still be used.
nix_store = [ "dep:cxx", "dep:bindgen", "dep:cxx-build" ]

# Tokio.
#
# When disabled, any part depending on tokio is unavailable.
tokio = [ "dep:tokio", "dep:async-stream" ]
