[package]
name = "attic-server"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "attic_server"
path = "src/lib.rs"

[[bin]]
name = "atticd"
path = "src/main.rs"
doc = false

[[bin]]
name = "atticadm"
path = "src/adm/main.rs"
doc = false

[dependencies]
attic = { path = "../attic", default-features = false }

anyhow = "1.0.68"
async-trait = "0.1.60"
aws-config = "0.52.0"
aws-sdk-s3 = "0.22.0"
axum = "0.6.1"
axum-macros = "0.3.0"
base64 = "0.20.0"
bytes = "1.3.0"
chrono = "0.4.23"
clap = { version = "4.0", features = ["derive"] }
derivative = "2.2.0"
digest = "0.10.6"
displaydoc = "0.2.3"
enum-as-inner = "0.5.1"
futures = "0.3.25"
hex = "0.4.3"
humantime = "2.1.0"
humantime-serde = "1.1.1"
itoa = "1.0.5"
jsonwebtoken = "8.2.0"
lazy_static = "1.4.0"
maybe-owned = "0.3.4"
rand = "0.8.5"
regex = "1.7.0"
ryu = "1.0.12"
sha2 = { version = "0.10.6", features = ["asm"] }
serde = "1.0.151"
serde_json = "1.0.91"
serde_with = "2.1.0"
tokio-util = { version = "0.7.4", features = [ "io" ] }
toml = "0.5.10"
tower-http = { version = "0.3.5", features = [ "catch-panic" ] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
uuid = { version = "1.2.2", features = ["v4"] }
console-subscriber = { version = "0.1.8", optional = true }
xdg = "2.4.1"

[dependencies.async-compression]
version = "0.3.15"
features = [
	"tokio",
	"xz",
	"zstd",
	"brotli",
]

[dependencies.sea-orm]
version = "0.10.6"
features = [
	"runtime-tokio-rustls",
	"macros",
	"sqlx-postgres",
	"sqlx-sqlite",
	"debug-print",
]

[dependencies.sea-orm-migration]
version = "0.10.6"

[dependencies.tokio]
version = "1.23.0"
features = [
	"fs",
	"io-util",
	"macros",
	"process",
	"rt",
	"rt-multi-thread",
	"sync",
]

[features]
tokio-console = ["dep:console-subscriber"]
