name: Build
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-11
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Obtain current username
        run: |
          echo ACTION_USER=$USER >> $GITHUB_ENV

      - uses: DeterminateSystems/nix-installer-action@2ec668c45628a4029e59357600d6b73107b0843b
        continue-on-error: true # Self-hosted runners already have Nix installed
        with:
          extra-conf: |
            trusted-users = root ${{ env.ACTION_USER }}

      - name: Install Attic
        run: |
          if ! command -v attic &> /dev/null; then
            ./.github/install-attic-ci.sh
          fi

      - name: Configure Attic
        run: |
          : "${ATTIC_SERVER:=https://staging.attic.rs/}"
          : "${ATTIC_CACHE:=attic-ci}"
          echo ATTIC_CACHE=$ATTIC_CACHE >>$GITHUB_ENV
          export PATH=$HOME/.nix-profile/bin:$PATH # FIXME
          attic login --set-default ci "$ATTIC_SERVER" "$ATTIC_TOKEN"
          attic use "$ATTIC_CACHE"
        env:
          ATTIC_SERVER: ${{ secrets.ATTIC_SERVER }}
          ATTIC_CACHE: ${{ secrets.ATTIC_CACHE }}
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}

      - name: Build and run tests
        run: |
          system=$(nix-instantiate --eval -E 'builtins.currentSystem')
          echo system=$system >>$GITHUB_ENV
          tests=$(nix build .#internal."$system".attic-tests --no-link --print-out-paths -L)
          find "$tests/bin" -exec {} \;

      # TODO: Just take a diff of the list of store paths, also abstract all of this out
      - name: Push build artifacts
        run: |
          export PATH=$HOME/.nix-profile/bin:$PATH # FIXME
          if [ -n "$ATTIC_TOKEN" ]; then
            nix build .#internal."$system".attic-tests .#internal."$system".cargoArtifacts --no-link --print-out-paths -L | \
              xargs attic push "ci:$ATTIC_CACHE"
          fi
