name: Sync fork and build attic

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches:
      - auto-sync
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 5

      - name: Rebase from upstream
        uses: imba-tjd/rebase-upstream-action@master
        with:
          upstream: zhaofengli/attic
          branch: main
      - name: Install nix and enable substituters
        uses: cachix/install-nix-action@v22
        with:
          nix_path: 'nixpkgs=channel:nixos-unstable'
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            substituters = https://cache.nixos.org https://staging.attic.rs/attic-ci https://ataraxiadev-foss.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= attic-ci:U5Sey4mUxwBXM3iFapmP0/ogODXywKLRNgRPQpEXxbo= ataraxiadev-foss.cachix.org-1:ws/jmPRUF5R8TkirnV1b525lP9F/uTBsz2KraV61058=
      - name: Setup cachix
        uses: cachix/cachix-action@v12
        with:
          name: ataraxiadev-foss
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build attic for all platforms
        run: nix shell -f '<nixpkgs>' nix-build-uncached -c nix-build-uncached ci.nix